name: Build BorderlessGaming

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1

    - name: Build solution
      run: msbuild BorderlessGaming.sln /p:Configuration=Release

    - name: Upload BorderlessGaming executable
      uses: actions/upload-artifact@v4.6.2
      with:
        name: BorderlessGaming
        path: BorderlessGaming\bin\Release\BorderlessGaming.exe
