name: Build BorderlessGaming

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore BorderlessGaming.sln
      
    - name: Install Inno Setup (ISCC)
      run: choco install innosetup --no-progress -y

    - name: Add SignTool to PATH
      run: |
        echo "C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86" >> $env:GITHUB_PATH
    
    - name: Build solution
      run: msbuild BorderlessGaming.sln /p:Configuration=Release /p:SignAssembly=false  /p:CI=true

    - name: Build installer with Inno Setup
      run: iscc Installers\BorderlessGaming_Standalone_Admin.iss
      
    - name: Upload executable
      uses: actions/upload-artifact@v4.6.2
      with:
        name: BorderlessGaming
        path: Installers\*setup.exe
