name: Build BorderlessGaming

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore BorderlessGaming.sln

    - name: Build solution
      run: msbuild BorderlessGaming.sln /p:Configuration=Release /p:SignAssembly=false

    - name: Upload executable
      uses: actions/upload-artifact@v4.6.2
      with:
        name: BorderlessGaming
        path: BorderlessGaming\bin\Release\BorderlessGaming.exe
